// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gi7b0OqsSgENr82mxF9Yogim7MOMEdE',
    appId: '1:838348876581:web:3fcd8c0bcb3942e2ba88cc',
    messagingSenderId: '838348876581',
    projectId: 'elxer-tasks',
    authDomain: 'elxer-tasks.firebaseapp.com',
    storageBucket: 'elxer-tasks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzCuy0J2grbrBp05NUyAgKvKHQ-UzUCo',
    appId: '1:838348876581:android:a24c8ba2ff18cb43ba88cc',
    messagingSenderId: '838348876581',
    projectId: 'elxer-tasks',
    storageBucket: 'elxer-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX11Ei5Gs4TFRtzxPC6xgU93owORpJR28',
    appId: '1:838348876581:ios:c9b2fe0f022b3614ba88cc',
    messagingSenderId: '838348876581',
    projectId: 'elxer-tasks',
    storageBucket: 'elxer-tasks.appspot.com',
    iosBundleId: 'com.anmolthedeveloper.elxer.elxerTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX11Ei5Gs4TFRtzxPC6xgU93owORpJR28',
    appId: '1:838348876581:ios:9bbc05137a32885eba88cc',
    messagingSenderId: '838348876581',
    projectId: 'elxer-tasks',
    storageBucket: 'elxer-tasks.appspot.com',
    iosBundleId: 'com.anmolthedeveloper.elxer.elxerTasks.RunnerTests',
  );
}
